### ISSUE TITLE
Mastodonのまとめてこれくしょん対応

### ISSUE THREAD

**Issue by Akkiesoft** [Akkiesoft/mikutter_pictcollect#1]
やろうな

先生による解説:
* https://mstdn.kanagu.info/@cobodo/100603907293288889
* https://mstdn.kanagu.info/@cobodo/100603912061210834
* https://mstdn.kanagu.info/@cobodo/100603926871182523

**Comment by cobodo** [comment]
URIからモデルを取得する方法について補足です。

https://github.com/Akkiesoft/mikutter_pictcollect/blob/master/pictcollect.rb#L142
> \# osa_kさんのshow_tweetを参考にした

とありますが、まさに先日、show_tweetを任意Model対応にしました。
https://github.com/cobodo/show_tweet/blob/req/any-model/show_tweet.rb#L26
↑このコードは、mikutter本体の core/mui/cairo_sub_parts_quote.rb とほぼ同じです。
https://dev.mikutter.hachune.net/projects/mikutter/repository/revisions/master/entry/core/mui/cairo_sub_parts_quote.rb#L33

**Comment by Akkiesoft** [comment]
@cobodo  （ほぼコピペですが…）できました！ありがとうございます。
